### ISSUE TITLE
Feedback after testing with Austin

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/grants.buidlguidl.com#85]
Just dumping it in here.

- [x] We tried to sign the /apply message and it failed (we were connected on Mainnet, and it said something like "wrong network" switch to OP). We should allow to sign on any of the two. Fixed on #90 
- [x] Remove askAmount from the signature message on /apply. Fixed on #90 
- [x] /my-grants should hide the amount when the status is "proposed". Only admins need to see that on /admin (0.25 as default... they will be able to edit when #83 is done). Fixed on #90 
- [ ] /my-grants show a link of the TXs sent (approved / completed). <ins>50 % sent TX</ins>

 We can create separate issues/PR. But maybe 1 & 2 ... 3 & 4 can go together.

I'll start tackling some of these.

**Comment by Pabl0cks** [comment]
Tackling this => `Remove askAmount from the signature message on /apply`
